version: "3"
services:
  minio:
    image: "docker.io/minio/minio:${MINIO_RELEASE:-RELEASE.2023-11-01T01-57-10Z}"
    hostname: s3
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: minioroot
    restart: always
    healthcheck:
      test: curl --fail http://localhost:9001 || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
